language: kotlin
sudo: false

jdk:
  - oraclejdk8
  - oraclejdk9

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

before_install:
  - sudo mysql -e "use mysql;"
  - sudo mysql -e "update user set authentication_string=PASSWORD('root') where User='root';"
  - sudo mysql -e "update user set plugin='mysql_native_password';"
  - sudo mysql -e "FLUSH PRIVILEGES;"
  - sudo mysql_upgrade
  - sudo service mysql restart
  - mysql -e 'DROP DATABASE IF EXISTS test;'
  - mysql -e 'CREATE DATABASE test;'

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

